package dependencies

object Version {
    const val hilt="2.44"
    const val fragment_ktx="1.5.7"
    const val retrofit="2.9.0"
    const val okhttp="4.9.0"
    const val coroutine="1.6.3"
    const val lifecycle="2.6.1"
    const val nav="2.5.3"
    const val glide="4.12.0"
    const val room="2.5.1"
    const val glide_compose="1.0.0-alpha.1"
    const val nav_version = "2.6.0"
    const val nav_hilt="1.0.0"
    const val paging_runtime="3.1.1"
    const val paging_compose="3.2.0-beta01"
    const val junit="4.13.2"
    const val truth_version = "1.1.3"
    const val turbine="0.7.0"
    const val coroutin_test="1.6.1"
    const val mockito_kotlin="3.2.0"
    const val core_testing="2.2.0"
    const val jUnit_androidTest="1.1.5"
    const val espresso_core="3.5.1"
    const val compose_bom="2022.10.00"
    const val core_ktx="1.10.1"
    const val activity_component="1.7.2"
    const val viewmodel_compose="2.6.1"
}